picklepete/pyicloud

pyicloud/services/findmyiphone.py
refresh locations now includes all devices associated with your family,
not just the main account used.
=> Enable family mode

pyicloud/base.py
We already generate and store the client ID in self.client_id, so
no need to re-generate it in refresh_validate().
=> Don't generate clientId twice

pyicloud/base.py, pyicloud/services/__init__.py, pyicloud/services/reminders.py
I noticed that this (very nice) library does not support Reminders, so I've added them:
```
r = api.reminders
```
creates the reminder service. The variable `r.list` contains the current reminders. `r.collections` is the contains which reminder lists are available (e.g. Tasks, Groceries, etc.). New reminders can be posted with `r.post(title, description = "", collection=None)`. `collection` must be a string from `r.collections` or `None` in which case the default list is used.
=> Adding Reminder support

pyicloud/__init__.py, pyicloud/base.py, pyicloud/exceptions.py
Allows easier debugging of failing API calls. We filter out iCloud
password so that debug logs can be attached to bug reports, etc.
Errors are raised as PyiCloudAPIResponseError with a reason and
code property, in addition to being logged, which allows them to
be handled by client code, or will at least give a clearer idea
about the issue than e.g. opaque key errors when trying to access
non existent properties of the JSON response.
=> Add centralized logging of iCloud API requests

README.rst, pyicloud/base.py, pyicloud/exceptions.py
When 2FA is enabled in iCloud most iCloud services are unavailable
without first going through the 2FA handshake. We now have API to
initiate the 2FA, which can be used by more advanced API clients.
The built in command line 'icloud' application has not been updated,
as listing and managing devices though Find my iPhone is one of the
services that do not require 2FA.
Fixes issue #66.
=> Add support for two-factor authentication (2FA)

pyicloud/services/reminders.py
I found reminder post function did not work in my environment.(Python 3.5.1)
I got below error message when calling `api.reminder.post()`
```
...
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyicloud-0.8.3-py3.5.egg/pyicloud/services/reminders.py", line 107, in post
"ClientState": {"Collections": self.collections.values()}
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 230, in dumps
return _default_encoder.encode(obj)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0) …
```
=> fix reminder post function for python3

README.rst
For 2FA code to wrk it needs access to the `click` library
=> Fixed missing import

pyicloud/services/photos.py, requirements.txt
Thanks for the great project! This is a PR regarding the creation time of photos.
Previously, the creation time of a photo would be in the local time zone and not time zone aware. This makes is hard to reason about the time the photo was created. This PR sets the time to UTC and makes it time zone aware.
Also switch to ISO 8601 as the output. This is what the pervious code was doing, except time zone information will be included.
Is there a reason why the the creation time is converted to a string? I think it would be more powerful to leave it as a `datetime` object. For this PR, I kept it as a string in case there was a reason for doing so.
=> Make photo creation time zone aware

pyicloud/services/reminders.py
Using the python `datetime` module, you can now add a due date for reminders that are created through this client:
```python
r = api.reminders
r.post(title, description = "", dueDate = datetime(2016, 12, 17, 20))
```
=> Add due date functionality for reminders

pyicloud/base.py
I'm writing some integration tests for my [icloud_photos_downloader](https://github.com/ndbroadbent/icloud_photos_downloader) script, and I'm using [vcrpy](https://vcrpy.readthedocs.io) to record and replay HTTP requests. This change lets me reuse the same client_id so that vcrpy will find the matching HTTP request.
=> Allow client_id to be overridden in __init__ (for replayable HTTP requests in pyvcr tests)

pyicloud/services/photos.py
Fixes #180 
If `assetDate['value']` is an invalid timestamp, just return 1/1/1970
=> Fix 'ValueError: year is out of range' when year is set to 0000

pyicloud/services/contacts.py
Fixes #202 by removing call to `self._contacts_refresh_url` which resolves issues with api.contacts.all() returning a 400 error.
=> fix Contacts services to return iphone contacts

pyicloud/services/photos.py
The __str__ method was crashing when an album title contained UTF-8 characters, such as an umlaut: "Jörg"
=> Fix PhotoAlbum#__str__ for UTF-8 album titles

pyicloud/base.py, pyicloud/exceptions.py
- while refreshing client after 20 min of non request
Fixes #156
=> Fix 450 error

pyicloud/services/findmyiphone.py
Currently `api.iphone.play_sound()` raises an attribute error. This PR sets a default value when the device isn't being created from a response dictionary.
Traceback : 
```shell
Traceback (most recent call last):
File "/Users/pollet/dev/home-assistant/core/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
connection.context(msg),
File "/Users/pollet/dev/home-assistant/core/homeassistant/core.py", line 1223, in async_call
await asyncio.shield(self._execute_service(handler, service_call))
File "/Users/pollet/dev/home-assistant/core/homeassistant/core.py", line 1250, in _execute_service
await self._hass.async_add_executor_job(handler.func, service_call)
File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/ …
```
=> Fix AppleDevice.play_sound() : AttributeError on 'with_family'

pyicloud/services/photos.py
Added working delete function for CPLAssets.
Fixes #239
=> Added working delete function for photos

.travis.yml, pyicloud/__init__.py, pyicloud/base.py, pyicloud/cmdline.py, pyicloud/exceptions.py, pyicloud/services/__init__.py, pyicloud/services/account.py, pyicloud/services/calendar.py, pyicloud/services/contacts.py, pyicloud/services/findmyiphone.py, pyicloud/services/photos.py, pyicloud/services/reminders.py, pyicloud/services/ubiquity.py, pyicloud/utils.py, pylintrc, requirements_test.txt, tests/__init__.py, tests/test_sanity.py
=> Replace PEP8 by pylint

pyicloud/services/findmyiphone.py
This will allow users to access their accessories (ex. Airpods) in the FindMyiPhone service.
Functionality is the same but there are more devices listed.
*same functionality as before*
None
=> Allow accessories to be retrieved from the FindMyiPhone service

.gitignore, .travis.yml, setup.py
=> CI & setup updates

README.rst, pyicloud/services/drive.py
The drive service only supports the bare minimum right now, improve
this situation.
=> Add new file operations mkdir, rename, delete and upload to drive service.

pyicloud/services/photos.py
Some albums can have null names, which make the current code bash crashing. This changes avoid crash by skipping those kind of albums
- This PR fixes or closes issue: fixes #285
=> Fix albumNameEnc can be null in Photos

pyicloud/services/drive.py
iCloud returns 400 Bad Request for 0-byte files. This resolves the issue by skipping the request and returning an empty response.
=> Fix downloading zero-byte files

requirements.txt
The stringent dependency on `click` (>=6.1, <=7.0 I think) causes conflicts with other packages. I have
* checked the `click` change log to check that the functionality in `pyicloud` is not affected by this change;
* run the tests with `click` 8.0.3, which pass;
* updated `requirements.txt` to change the required version of `click`.
(Fixes #289)
=> Update click version to reduce potential for dependency conflict

README.rst
This simple PR updates the README with a few minor items:
- Use proper `print` functions. The existing README use print statements, which are from ancient python versions and don't work on any current python version.
- Remove unicode markers from sample strings. This just adds noise and hurts legibility, and, again, is no longer a thing.
- Explicitly mark all code blocks. Currently, autodetection is not getting them all right, and the highlighting for many of the blocks is off. These improvements will make all of them render properly (both on GitHub and PyPI).
I'd suggest reviewing each commit individually, it's a lot easier to read when doing so.
Skipping the checklist since the changes are documentation-only.
=> Polish readme

requirements_test.txt
- Pin all test requirements to exact versions. Test requirements should be pinned strictly to avoid unintentional breakage.
- Remove mock requirement which is a backport and now part of standard library since Python 3.3.
- https://pypi.org/project/mock/
```python
```
=> Clean and pin test requirements

pyicloud/base.py
=> Fix for 450 reauthentication failure bug

README.rst, pyicloud/base.py, pyicloud/cmdline.py, tests/__init__.py
Authentication will fail if the country/region setting of the Apple ID is China mainland. This PR fixes it.
```python
icloud = pyicloud.PyiCloudService(
username, password,
cookie_directory=cookie_directory,
client_id=client_id,
china_mainland=True,
)
```
- This PR fixes or closes issue: fixes #419 
=> Should use different endpoint if the country/region setting of the Apple ID is China mainland.
