picklepete/pyicloud

pyicloud/base.py

Add X-APPLE-WEB-KB cookie handling to prevent e-mail from Apple every time script is run.

Add X-APPLE-WEB-KB cookie handling

---

pyicloud/base.py

Add optional verify parameter to allow verification of SSL certificates

---

pyicloud/base.py

Instead of trying to look for a specific cookie to save, discarding all
others, and persisting the cookies manually using pickle, we build on
the functionality of cookielib, which already has functionality to save
and load cookiejars. The request library is documented to work with any
subclass of cookielib.CookieJar.
This ensures that we only save persistent cookies (which includes the
X-APPLE-WEB-KB cookie), and skip session cookies, which should make the
code more future proof in case Apple adds more persistent cookies.
This also fixes #44, which was still occurring because we were
persisting the cookies of the request, not the session, and when
logging in with a persisted cookie the resulting request did not
have the X-APPLE-WEB-KB set, so we ended up overwriting the cookie
file with …

Rework cookie persistence handling

---

README.rst

Seems like a leftover from git. Awesome project!

README fix

---

pyicloud/base.py
pyicloud/services/__init__.py
pyicloud/services/account.py

Support for ICloud Account service
for now only getDevices operaion
related to #34

Add ICloud Account service

---

pyicloud/services/findmyiphone.py

Bug fix for picklepete/pyicloud#90.  Adding this additional clientContent data resolves the 500 error.

Additional clientContext data for iphone play sound call - picklepete/pyicloud#90

---

README.rst
pyicloud/base.py
pyicloud/exceptions.py
pyicloud/services/photos.py
requirements.txt

Here's a pull request to merge in changes discussed in picklepete/pyicloud#136.  With the current released version of pyicloud being broken I figured it was best to get this discussion started.

Reimplement PhotosService to use the new ckdatabasews back-end

---

pyicloud/services/calendar.py

I added function that return calendars - names, guid, url and more

added new function to calendars

---

pyicloud/base.py
pyicloud/exceptions.py

Fix response is not defined

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/SUPPORT.md

Fix the issue templates to permits creating issue.

Fix issue templates

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/SUPPORT.md

Fix the issue templates to permits creating issue.

Fix issue templates (again)

---

.travis.yml
setup.py
tox.ini

Upgrade Python tests version

---

pyicloud/services/reminders.py

Fix Reminder KeyError: 'description'.
But still : 
- will **WORK** with iOS < 13: because iCloud accounts did not updated their Reminder app with iOS 13.
- will **NOT WORK**: with iCloud account that updated the Reminder with iOS 13, it will lead us to https://support.apple.com/HT210220.
- This PR fixes or closes issue: fixes #211

Fix Reminder KeyError: 'description'

---

pyicloud/services/calendar.py

Fix Calendar KeyError: 'Event'
- This PR fixes or closes issue: fixes #219

Fix Calendar KeyError: 'Event'

---

pyicloud/services/contacts.py

Fix Contact limit to 500
- This PR fixes or closes issue: fixes #103 + closes #114

Fix Contact limit to 500

---

README.rst
pyicloud/services/photos.py

Additional key checking for photo version build-up

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_SAMPLES.md
CODE_SAMPLES.rst
README.rst

Add code samples to make the lib easier to use.
- This PR fixes or closes issue: fixes #188

Add code samples

---

setup.py

Include only the right package to setup

Include only the right package to setup

---

setup.py

Fix missing 'services' package

Fix missing 'services' package

---

scripts/clean.sh
scripts/common.sh
scripts/publish.sh

Add clean + publish scripts

---

.travis.yml
README.rst
pyicloud/base.py
pyicloud/cmdline.py
pyicloud/exceptions.py
pyicloud/services/account.py
pyicloud/services/calendar.py
pyicloud/services/contacts.py
pyicloud/services/findmyiphone.py
pyicloud/services/photos.py
pyicloud/services/reminders.py
pyicloud/services/ubiquity.py
pyicloud/utils.py
pyproject.toml
scripts/black.sh
scripts/check_format.sh
setup.py
tests/__init__.py
tests/test_cmdline.py

Back is black

---

README.rst

Add download badge

---

pyicloud/services/account.py
tests/__init__.py
tests/const.py
tests/const_account.py
tests/const_account_family.py
tests/const_findmyiphone.py
tests/const_login.py
tests/test_account.py
tests/test_cmdline.py

Add account family + storage services
```python
```

Add account family + storage services

---

pyicloud/base.py
pyicloud/cmdline.py
pyicloud/services/account.py
pyicloud/services/calendar.py
pyicloud/services/findmyiphone.py
pyicloud/services/photos.py
pyicloud/services/ubiquity.py
pyicloud/utils.py
tests/test_account.py
tests/test_cmdline.py

Fix urlencode in Photos service + account division + Python 2 first
Following this cheat sheet : http://python-future.org/compatible_idioms.html

Rework Python 2-3 compat

---

pyicloud/base.py

Fix 450 RecursionError

---

pyicloud/services/drive.py

Fix Drive KeyError: 'extension'. Files without extensions do not have this field.

Fix Drive KeyError: 'extension'

---

pyicloud/services/drive.py

The webinterface to drive claims, that zero sized files are not supported
on Drive.
Uploading one seems to work however with the only caveat that no receipt
is returned. Handle this case by only adding receipt if available to the
_update_contentws() call.
This allows for feature parity with the bird/cloudd synced drive, which does
zero sized files.
Drive-By: Add a get_app_data() call to the Drive module. This seems to be
a replacement for ubiquity which seems to be deprecated.

Allow zero-sized files on Drive

---

CODE_SAMPLES.md

Add an example invocation to CODE_SAMPLES that would allow for
MITM interception as well as debug prints to the console.
Drive-By: blacken the code samples.
Drive-By: Make code samples compliant with python3 (print->print())
Fixes: #270
- This PR fixes or closes issue: fixes #270 

Add debugging example to CODE_SAMPLES.md

---

pyicloud/services/drive.py

Fix timestamp about api.drive.upload().
When I use api.drive.upload() to upload files, mtime and btime were always '1970-01-19 20:28:17'. I found Apple use 'ms' instead of 's'.

Fix Drive mtime and btime

---

README.rst

```python
drive_file = api.drive['Holiday Photos']['2013']['Sicily']['DSC08116.JPG']
drive_file.date_modified
```
Using the original `drive_file.modified` returned:
```
AttributeError: 'drive_file' object has no attribute 'modified'
```

Fix api.drive[].date_modified example

---

pyicloud/base.py

I was trying to use pyicloud on a shared system and got permissions errors for /tmp/pyicloud
This patch creates /tmp/pyicloud/username and sets read/writes permission for the current user only make the cookie jar also more secure. It also stores the cookies for 2fa in the same directory, see #310 
Obsoletes #315

Create safe cookiejar directory per user

---

README.rst
setup.py

Ready to release `v0.10.1`, which includes 2FA support among other things.

Release v1.10.1

---

.github/workflows/ci.yml
.github/workflows/publish.yml
pyproject.toml
setup.py
tox.ini

- Python 3.6 is end of life since December 2021. The minimum Python version required for pyicloud is now Python 3.7.
```python
```

Remove support for Python 3.6

---

tests/__init__.py
tests/test_account.py
tests/test_cmdline.py
tests/test_drive.py
tests/test_findmyiphone.py

- Fix and add missing docstrings.
- Sort imports.
- Remove not used imports.
- Move pylint disable to place where needed.
```python
```

Clean up tests
